import { CHARACTER_TYPE, type Character } from "./types";

export const CHARACTERS_LIST: Character[] = [
  {
    id: "satoshi",
    name: "сатоши",
    image_url: `${import.meta.env.BASE_URL}assets/satoshi.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "vi",
    name: "ви",
    image_url: `${import.meta.env.BASE_URL}assets/vi.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "levi",
    name: "леви",
    image_url: `${import.meta.env.BASE_URL}assets/levi.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "doc",
    name: "док",
    image_url: `${import.meta.env.BASE_URL}assets/doc.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "stalker",
    name: "сталкер",
    image_url: `${import.meta.env.BASE_URL}assets/stalker.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "tess",
    name: "тесс",
    image_url: `${import.meta.env.BASE_URL}assets/tess.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "graviel",
    name: "гравиель",
    image_url: `${import.meta.env.BASE_URL}assets/graviel.png`,
    type: CHARACTER_TYPE.TROOPER,
  },
  {
    id: "arnie",
    name: "арни",
    image_url: `${import.meta.env.BASE_URL}assets/arnie.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "cyclops",
    name: "циклоп",
    image_url: `${import.meta.env.BASE_URL}assets/cyclops.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "sparkle",
    name: "искра",
    image_url: `${import.meta.env.BASE_URL}assets/sparkle.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "hurricane",
    name: "ураган",
    image_url: `${import.meta.env.BASE_URL}assets/hurricane.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "shenji",
    name: "шеднжи",
    image_url: `${import.meta.env.BASE_URL}assets/shenji.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "molly",
    name: "молли",
    image_url: `${import.meta.env.BASE_URL}assets/molly.png`,
    type: CHARACTER_TYPE.SHOTGUN,
  },
  {
    id: "ghost",
    name: "призрак",
    image_url: `${import.meta.env.BASE_URL}assets/ghost.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "freddie",
    name: "фредди",
    image_url: `${import.meta.env.BASE_URL}assets/freddie.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "angel",
    name: "ангел",
    image_url: `${import.meta.env.BASE_URL}assets/angel.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "raven",
    name: "ворон",
    image_url: `${import.meta.env.BASE_URL}assets/raven.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "alice",
    name: "алиса",
    image_url: `${import.meta.env.BASE_URL}assets/alice.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "twinkle",
    name: "твинкл",
    image_url: `${import.meta.env.BASE_URL}assets/twinkle.png`,
    type: CHARACTER_TYPE.SCOUT,
  },
  {
    id: "blot",
    name: "блот",
    image_url: `${import.meta.env.BASE_URL}assets/blot.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "firefly",
    name: "огонёк",
    image_url: `${import.meta.env.BASE_URL}assets/firefly.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "slayer",
    name: "губитель",
    image_url: `${import.meta.env.BASE_URL}assets/slayer.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "mirage",
    name: "мираж",
    image_url: `${import.meta.env.BASE_URL}assets/mirage.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "lynx",
    name: "линкс",
    image_url: `${import.meta.env.BASE_URL}assets/lynx.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "blizzard",
    name: "вьюга",
    image_url: `${import.meta.env.BASE_URL}assets/blizzard.png`,
    type: CHARACTER_TYPE.SNIPER,
  },
  {
    id: "smog",
    name: "смог",
    image_url: `${import.meta.env.BASE_URL}assets/smog.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "dragoon",
    name: "драгун",
    image_url: `${import.meta.env.BASE_URL}assets/dragoon.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "bastion",
    name: "бастион",
    image_url: `${import.meta.env.BASE_URL}assets/bastion.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "bertha",
    name: "берта",
    image_url: `${import.meta.env.BASE_URL}assets/bertha.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "leviathan",
    name: "левиафан",
    image_url: `${import.meta.env.BASE_URL}assets/leviathan.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "ramsey",
    name: "рамзи",
    image_url: `${import.meta.env.BASE_URL}assets/ramsey.png`,
    type: CHARACTER_TYPE.TANK,
  },
  {
    id: "kwon",
    name: "квон",
    image_url: `${import.meta.env.BASE_URL}assets/kwon.png`,
    type: CHARACTER_TYPE.TANK,
  },
];
