import { DRAFT_ACTION_TYPE } from "./types";

export const DRAFT_ACTIONS: DRAFT_ACTION_TYPE[] = [
  DRAFT_ACTION_TYPE.BAN,
  DRAFT_ACTION_TYPE.DOUBLE_BAN,
  DRAFT_ACTION_TYPE.PICK,
  DRAFT_ACTION_TYPE.DOUBLE_PICK,
  DRAFT_ACTION_TYPE.DOUBLE_PICK,
  DRAFT_ACTION_TYPE.PICK,
  DRAFT_ACTION_TYPE.DOUBLE_BAN,
  DRAFT_ACTION_TYPE.BAN,
  DRAFT_ACTION_TYPE.DOUBLE_PICK,
  DRAFT_ACTION_TYPE.DOUBLE_PICK,
];
